const COUNTRIES: { [key: string]: any } = {
  AFG: {
    label: 'Afghanistan',
    value: 'AFG',
    iconSrc:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png',
    code: '+93',
  },
  ALA: {
    label: 'Åland Islands',
    value: 'ALA',
    iconSrc: 'https://flagcdn.com/w320/ax.png',
    code: '+35818',
  },
  ALB: {
    label: 'Albania',
    value: 'ALB',
    iconSrc: 'https://flagcdn.com/w320/al.png',
    code: '+355',
  },
  DZA: {
    label: 'Algeria',
    value: 'DZA',
    iconSrc: 'https://flagcdn.com/w320/dz.png',
    code: '+213',
  },
  ASM: {
    label: 'American Samoa',
    value: 'ASM',
    iconSrc: 'https://flagcdn.com/w320/as.png',
    code: '+1684',
  },
  AND: {
    label: 'Andorra',
    value: 'AND',
    iconSrc: 'https://flagcdn.com/w320/ad.png',
    code: '+376',
  },
  AGO: {
    label: 'Angola',
    value: 'AGO',
    iconSrc: 'https://flagcdn.com/w320/ao.png',
    code: '+244',
  },
  AIA: {
    label: 'Anguilla',
    value: 'AIA',
    iconSrc: 'https://flagcdn.com/w320/ai.png',
    code: '+1264',
  },
  ATA: {
    label: 'Antarctica',
    value: 'ATA',
    iconSrc: 'https://flagcdn.com/w320/aq.png',
    code: null,
  },
  ATG: {
    label: 'Antigua and Barbuda',
    value: 'ATG',
    iconSrc: 'https://flagcdn.com/w320/ag.png',
    code: '+1268',
  },
  ARG: {
    label: 'Argentina',
    value: 'ARG',
    iconSrc: 'https://flagcdn.com/w320/ar.png',
    code: '+54',
  },
  ARM: {
    label: 'Armenia',
    value: 'ARM',
    iconSrc: 'https://flagcdn.com/w320/am.png',
    code: '+374',
  },
  ABW: {
    label: 'Aruba',
    value: 'ABW',
    iconSrc: 'https://flagcdn.com/w320/aw.png',
    code: '+297',
  },
  AUS: {
    label: 'Australia',
    value: 'AUS',
    iconSrc: 'https://flagcdn.com/w320/au.png',
    code: '+61',
  },
  AUT: {
    label: 'Austria',
    value: 'AUT',
    iconSrc: 'https://flagcdn.com/w320/at.png',
    code: '+43',
  },
  BHS: {
    label: 'Bahamas',
    value: 'BHS',
    iconSrc: 'https://flagcdn.com/w320/bs.png',
    code: '+1242',
  },
  BHR: {
    label: 'Bahrain',
    value: 'BHR',
    iconSrc: 'https://flagcdn.com/w320/bh.png',
    code: '+973',
  },
  BGD: {
    label: 'Bangladesh',
    value: 'BGD',
    iconSrc: 'https://flagcdn.com/w320/bd.png',
    code: '+880',
  },
  BRB: {
    label: 'Barbados',
    value: 'BRB',
    iconSrc: 'https://flagcdn.com/w320/bb.png',
    code: '+1246',
  },
  BLR: {
    label: 'Belarus',
    value: 'BLR',
    iconSrc: 'https://flagcdn.com/w320/by.png',
    code: '+375',
  },
  BEL: {
    label: 'Belgium',
    value: 'BEL',
    iconSrc: 'https://flagcdn.com/w320/be.png',
    code: '+32',
  },
  BLZ: {
    label: 'Belize',
    value: 'BLZ',
    iconSrc: 'https://flagcdn.com/w320/bz.png',
    code: '+501',
  },
  BEN: {
    label: 'Benin',
    value: 'BEN',
    iconSrc: 'https://flagcdn.com/w320/bj.png',
    code: '+229',
  },
  BMU: {
    label: 'Bermuda',
    value: 'BMU',
    iconSrc: 'https://flagcdn.com/w320/bm.png',
    code: '+1441',
  },
  BTN: {
    label: 'Bhutan',
    value: 'BTN',
    iconSrc: 'https://flagcdn.com/w320/bt.png',
    code: '+975',
  },
  BOL: {
    label: 'Bolivia',
    value: 'BOL',
    iconSrc: 'https://flagcdn.com/w320/bo.png',
    code: '+591',
  },
  BIH: {
    label: 'Bosnia and Herzegovina',
    value: 'BIH',
    iconSrc: 'https://flagcdn.com/w320/ba.png',
    code: '+387',
  },
  BWA: {
    label: 'Botswana',
    value: 'BWA',
    iconSrc: 'https://flagcdn.com/w320/bw.png',
    code: '+267',
  },
  BVT: {
    label: 'Bouvet Island',
    value: 'BVT',
    iconSrc: 'https://flagcdn.com/w320/bv.png',
    code: '+47',
  },
  BRA: {
    label: 'Brazil',
    value: 'BRA',
    iconSrc: 'https://flagcdn.com/w320/br.png',
    code: '+55',
  },
  IOT: {
    label: 'British Indian Ocean Territory',
    value: 'IOT',
    iconSrc: 'https://flagcdn.com/w320/io.png',
    code: '+246',
  },
  VGB: {
    label: 'British Virgin Islands',
    value: 'VGB',
    iconSrc: 'https://flagcdn.com/w320/vg.png',
    code: '+1284',
  },
  BRN: {
    label: 'Brunei',
    value: 'BRN',
    iconSrc: 'https://flagcdn.com/w320/bn.png',
    code: '+673',
  },
  BGR: {
    label: 'Bulgaria',
    value: 'BGR',
    iconSrc: 'https://flagcdn.com/w320/bg.png',
    code: '+359',
  },
  BFA: {
    label: 'Burkina Faso',
    value: 'BFA',
    iconSrc: 'https://flagcdn.com/w320/bf.png',
    code: '+226',
  },
  BDI: {
    label: 'Burundi',
    value: 'BDI',
    iconSrc: 'https://flagcdn.com/w320/bi.png',
    code: '+257',
  },
  KHM: {
    label: 'Cambodia',
    value: 'KHM',
    iconSrc: 'https://flagcdn.com/w320/kh.png',
    code: '+855',
  },
  CMR: {
    label: 'Cameroon',
    value: 'CMR',
    iconSrc: 'https://flagcdn.com/w320/cm.png',
    code: '+237',
  },
  CAN: {
    label: 'Canada',
    value: 'CAN',
    iconSrc: 'https://flagcdn.com/w320/ca.png',
    code: '+1',
  },
  CPV: {
    label: 'Cape Verde',
    value: 'CPV',
    iconSrc: 'https://flagcdn.com/w320/cv.png',
    code: '+238',
  },
  BES: {
    label: 'Caribbean Netherlands',
    value: 'BES',
    iconSrc: 'https://flagcdn.com/w320/bq.png',
    code: '+599',
  },
  CYM: {
    label: 'Cayman Islands',
    value: 'CYM',
    iconSrc: 'https://flagcdn.com/w320/ky.png',
    code: '+1345',
  },
  CAF: {
    label: 'Central African Republic',
    value: 'CAF',
    iconSrc: 'https://flagcdn.com/w320/cf.png',
    code: '+236',
  },
  TCD: {
    label: 'Chad',
    value: 'TCD',
    iconSrc: 'https://flagcdn.com/w320/td.png',
    code: '+235',
  },
  CHL: {
    label: 'Chile',
    value: 'CHL',
    iconSrc: 'https://flagcdn.com/w320/cl.png',
    code: '+56',
  },
  CHN: {
    label: 'China',
    value: 'CHN',
    iconSrc: 'https://flagcdn.com/w320/cn.png',
    code: '+86',
  },
  CXR: {
    label: 'Christmas Island',
    value: 'CXR',
    iconSrc: 'https://flagcdn.com/w320/cx.png',
    code: '+61',
  },
  CCK: {
    label: 'Cocos (Keeling) Islands',
    value: 'CCK',
    iconSrc: 'https://flagcdn.com/w320/cc.png',
    code: '+61',
  },
  COL: {
    label: 'Colombia',
    value: 'COL',
    iconSrc: 'https://flagcdn.com/w320/co.png',
    code: '+57',
  },
  COM: {
    label: 'Comoros',
    value: 'COM',
    iconSrc: 'https://flagcdn.com/w320/km.png',
    code: '+269',
  },
  COK: {
    label: 'Cook Islands',
    value: 'COK',
    iconSrc: 'https://flagcdn.com/w320/ck.png',
    code: '+682',
  },
  CRI: {
    label: 'Costa Rica',
    value: 'CRI',
    iconSrc: 'https://flagcdn.com/w320/cr.png',
    code: '+506',
  },
  HRV: {
    label: 'Croatia',
    value: 'HRV',
    iconSrc: 'https://flagcdn.com/w320/hr.png',
    code: '+385',
  },
  CUB: {
    label: 'Cuba',
    value: 'CUB',
    iconSrc: 'https://flagcdn.com/w320/cu.png',
    code: '+53',
  },
  CUW: {
    label: 'Curaçao',
    value: 'CUW',
    iconSrc: 'https://flagcdn.com/w320/cw.png',
    code: '+599',
  },
  CYP: {
    label: 'Cyprus',
    value: 'CYP',
    iconSrc: 'https://flagcdn.com/w320/cy.png',
    code: '+357',
  },
  CZE: {
    label: 'Czechia',
    value: 'CZE',
    iconSrc: 'https://flagcdn.com/w320/cz.png',
    code: '+420',
  },
  DNK: {
    label: 'Denmark',
    value: 'DNK',
    iconSrc: 'https://flagcdn.com/w320/dk.png',
    code: '+45',
  },
  DJI: {
    label: 'Djibouti',
    value: 'DJI',
    iconSrc: 'https://flagcdn.com/w320/dj.png',
    code: '+253',
  },
  DMA: {
    label: 'Dominica',
    value: 'DMA',
    iconSrc: 'https://flagcdn.com/w320/dm.png',
    code: '+1767',
  },
  DOM: {
    label: 'Dominican Republic',
    value: 'DOM',
    iconSrc: 'https://flagcdn.com/w320/do.png',
    code: '+1809,829,849',
  },
  COD: {
    label: 'DR Congo',
    value: 'COD',
    iconSrc: 'https://flagcdn.com/w320/cd.png',
    code: '+243',
  },
  ECU: {
    label: 'Ecuador',
    value: 'ECU',
    iconSrc: 'https://flagcdn.com/w320/ec.png',
    code: '+593',
  },
  EGY: {
    label: 'Egypt',
    value: 'EGY',
    iconSrc: 'https://flagcdn.com/w320/eg.png',
    code: '+20',
  },
  SLV: {
    label: 'El Salvador',
    value: 'SLV',
    iconSrc: 'https://flagcdn.com/w320/sv.png',
    code: '+503',
  },
  GNQ: {
    label: 'Equatorial Guinea',
    value: 'GNQ',
    iconSrc: 'https://flagcdn.com/w320/gq.png',
    code: '+240',
  },
  ERI: {
    label: 'Eritrea',
    value: 'ERI',
    iconSrc: 'https://flagcdn.com/w320/er.png',
    code: '+291',
  },
  EST: {
    label: 'Estonia',
    value: 'EST',
    iconSrc: 'https://flagcdn.com/w320/ee.png',
    code: '+372',
  },
  SWZ: {
    label: 'Eswatini',
    value: 'SWZ',
    iconSrc: 'https://flagcdn.com/w320/sz.png',
    code: '+268',
  },
  ETH: {
    label: 'Ethiopia',
    value: 'ETH',
    iconSrc: 'https://flagcdn.com/w320/et.png',
    code: '+251',
  },
  FLK: {
    label: 'Falkland Islands',
    value: 'FLK',
    iconSrc: 'https://flagcdn.com/w320/fk.png',
    code: '+500',
  },
  FRO: {
    label: 'Faroe Islands',
    value: 'FRO',
    iconSrc: 'https://flagcdn.com/w320/fo.png',
    code: '+298',
  },
  FJI: {
    label: 'Fiji',
    value: 'FJI',
    iconSrc: 'https://flagcdn.com/w320/fj.png',
    code: '+679',
  },
  FIN: {
    label: 'Finland',
    value: 'FIN',
    iconSrc: 'https://flagcdn.com/w320/fi.png',
    code: '+358',
  },
  FRA: {
    label: 'France',
    value: 'FRA',
    iconSrc: 'https://flagcdn.com/w320/fr.png',
    code: '+33',
  },
  GUF: {
    label: 'French Guiana',
    value: 'GUF',
    iconSrc: 'https://flagcdn.com/w320/gf.png',
    code: '+594',
  },
  PYF: {
    label: 'French Polynesia',
    value: 'PYF',
    iconSrc: 'https://flagcdn.com/w320/pf.png',
    code: '+689',
  },
  ATF: {
    label: 'French Southern and Antarctic Lands',
    value: 'ATF',
    iconSrc: 'https://flagcdn.com/w320/tf.png',
    code: '+262',
  },
  GAB: {
    label: 'Gabon',
    value: 'GAB',
    iconSrc: 'https://flagcdn.com/w320/ga.png',
    code: '+241',
  },
  GMB: {
    label: 'Gambia',
    value: 'GMB',
    iconSrc: 'https://flagcdn.com/w320/gm.png',
    code: '+220',
  },
  GEO: {
    label: 'Georgia',
    value: 'GEO',
    iconSrc: 'https://flagcdn.com/w320/ge.png',
    code: '+995',
  },
  DEU: {
    label: 'Germany',
    value: 'DEU',
    iconSrc: 'https://flagcdn.com/w320/de.png',
    code: '+49',
  },
  GHA: {
    label: 'Ghana',
    value: 'GHA',
    iconSrc: 'https://flagcdn.com/w320/gh.png',
    code: '+233',
  },
  GIB: {
    label: 'Gibraltar',
    value: 'GIB',
    iconSrc: 'https://flagcdn.com/w320/gi.png',
    code: '+350',
  },
  GRC: {
    label: 'Greece',
    value: 'GRC',
    iconSrc: 'https://flagcdn.com/w320/gr.png',
    code: '+30',
  },
  GRL: {
    label: 'Greenland',
    value: 'GRL',
    iconSrc: 'https://flagcdn.com/w320/gl.png',
    code: '+299',
  },
  GRD: {
    label: 'Grenada',
    value: 'GRD',
    iconSrc: 'https://flagcdn.com/w320/gd.png',
    code: '+1473',
  },
  GLP: {
    label: 'Guadeloupe',
    value: 'GLP',
    iconSrc: 'https://flagcdn.com/w320/gp.png',
    code: '+590',
  },
  GUM: {
    label: 'Guam',
    value: 'GUM',
    iconSrc: 'https://flagcdn.com/w320/gu.png',
    code: '+1671',
  },
  GTM: {
    label: 'Guatemala',
    value: 'GTM',
    iconSrc: 'https://flagcdn.com/w320/gt.png',
    code: '+502',
  },
  GGY: {
    label: 'Guernsey',
    value: 'GGY',
    iconSrc: 'https://flagcdn.com/w320/gg.png',
    code: '+44',
  },
  GIN: {
    label: 'Guinea',
    value: 'GIN',
    iconSrc: 'https://flagcdn.com/w320/gn.png',
    code: '+224',
  },
  GNB: {
    label: 'Guinea-Bissau',
    value: 'GNB',
    iconSrc: 'https://flagcdn.com/w320/gw.png',
    code: '+245',
  },
  GUY: {
    label: 'Guyana',
    value: 'GUY',
    iconSrc: 'https://flagcdn.com/w320/gy.png',
    code: '+592',
  },
  HTI: {
    label: 'Haiti',
    value: 'HTI',
    iconSrc: 'https://flagcdn.com/w320/ht.png',
    code: '+509',
  },
  HMD: {
    label: 'Heard Island and McDonald Islands',
    value: 'HMD',
    iconSrc: 'https://flagcdn.com/w320/hm.png',
    code: null,
  },
  HND: {
    label: 'Honduras',
    value: 'HND',
    iconSrc: 'https://flagcdn.com/w320/hn.png',
    code: '+504',
  },
  HKG: {
    label: 'Hong Kong',
    value: 'HKG',
    iconSrc: 'https://flagcdn.com/w320/hk.png',
    code: '+852',
  },
  HUN: {
    label: 'Hungary',
    value: 'HUN',
    iconSrc: 'https://flagcdn.com/w320/hu.png',
    code: '+36',
  },
  ISL: {
    label: 'Iceland',
    value: 'ISL',
    iconSrc: 'https://flagcdn.com/w320/is.png',
    code: '+354',
  },
  IND: {
    label: 'India',
    value: 'IND',
    iconSrc: 'https://flagcdn.com/w320/in.png',
    code: '+91',
  },
  IDN: {
    label: 'Indonesia',
    value: 'IDN',
    iconSrc: 'https://flagcdn.com/w320/id.png',
    code: '+62',
  },
  IRN: {
    label: 'Iran',
    value: 'IRN',
    iconSrc: 'https://flagcdn.com/w320/ir.png',
    code: '+98',
  },
  IRQ: {
    label: 'Iraq',
    value: 'IRQ',
    iconSrc: 'https://flagcdn.com/w320/iq.png',
    code: '+964',
  },
  IRL: {
    label: 'Ireland',
    value: 'IRL',
    iconSrc: 'https://flagcdn.com/w320/ie.png',
    code: '+353',
  },
  IMN: {
    label: 'Isle of Man',
    value: 'IMN',
    iconSrc: 'https://flagcdn.com/w320/im.png',
    code: '+44',
  },
  ISR: {
    label: 'Israel',
    value: 'ISR',
    iconSrc: 'https://flagcdn.com/w320/il.png',
    code: '+972',
  },
  ITA: {
    label: 'Italy',
    value: 'ITA',
    iconSrc: 'https://flagcdn.com/w320/it.png',
    code: '+39',
  },
  CIV: {
    label: 'Ivory Coast',
    value: 'CIV',
    iconSrc: 'https://flagcdn.com/w320/ci.png',
    code: '+225',
  },
  JAM: {
    label: 'Jamaica',
    value: 'JAM',
    iconSrc: 'https://flagcdn.com/w320/jm.png',
    code: '+1876',
  },
  JPN: {
    label: 'Japan',
    value: 'JPN',
    iconSrc: 'https://flagcdn.com/w320/jp.png',
    code: '+81',
  },
  JEY: {
    label: 'Jersey',
    value: 'JEY',
    iconSrc: 'https://flagcdn.com/w320/je.png',
    code: '+44',
  },
  JOR: {
    label: 'Jordan',
    value: 'JOR',
    iconSrc: 'https://flagcdn.com/w320/jo.png',
    code: '+962',
  },
  KAZ: {
    label: 'Kazakhstan',
    value: 'KAZ',
    iconSrc: 'https://flagcdn.com/w320/kz.png',
    code: '+76,7',
  },
  KEN: {
    label: 'Kenya',
    value: 'KEN',
    iconSrc: 'https://flagcdn.com/w320/ke.png',
    code: '+254',
  },
  KIR: {
    label: 'Kiribati',
    value: 'KIR',
    iconSrc: 'https://flagcdn.com/w320/ki.png',
    code: '+686',
  },
  UNK: {
    label: 'Kosovo',
    value: 'UNK',
    iconSrc: 'https://flagcdn.com/w320/xk.png',
    code: '+383',
  },
  KWT: {
    label: 'Kuwait',
    value: 'KWT',
    iconSrc: 'https://flagcdn.com/w320/kw.png',
    code: '+965',
  },
  KGZ: {
    label: 'Kyrgyzstan',
    value: 'KGZ',
    iconSrc: 'https://flagcdn.com/w320/kg.png',
    code: '+996',
  },
  LAO: {
    label: 'Laos',
    value: 'LAO',
    iconSrc: 'https://flagcdn.com/w320/la.png',
    code: '+856',
  },
  LVA: {
    label: 'Latvia',
    value: 'LVA',
    iconSrc: 'https://flagcdn.com/w320/lv.png',
    code: '+371',
  },
  LBN: {
    label: 'Lebanon',
    value: 'LBN',
    iconSrc: 'https://flagcdn.com/w320/lb.png',
    code: '+961',
  },
  LSO: {
    label: 'Lesotho',
    value: 'LSO',
    iconSrc: 'https://flagcdn.com/w320/ls.png',
    code: '+266',
  },
  LBR: {
    label: 'Liberia',
    value: 'LBR',
    iconSrc: 'https://flagcdn.com/w320/lr.png',
    code: '+231',
  },
  LBY: {
    label: 'Libya',
    value: 'LBY',
    iconSrc: 'https://flagcdn.com/w320/ly.png',
    code: '+218',
  },
  LIE: {
    label: 'Liechtenstein',
    value: 'LIE',
    iconSrc: 'https://flagcdn.com/w320/li.png',
    code: '+423',
  },
  LTU: {
    label: 'Lithuania',
    value: 'LTU',
    iconSrc: 'https://flagcdn.com/w320/lt.png',
    code: '+370',
  },
  LUX: {
    label: 'Luxembourg',
    value: 'LUX',
    iconSrc: 'https://flagcdn.com/w320/lu.png',
    code: '+352',
  },
  MAC: {
    label: 'Macau',
    value: 'MAC',
    iconSrc: 'https://flagcdn.com/w320/mo.png',
    code: '+853',
  },
  MDG: {
    label: 'Madagascar',
    value: 'MDG',
    iconSrc: 'https://flagcdn.com/w320/mg.png',
    code: '+261',
  },
  MWI: {
    label: 'Malawi',
    value: 'MWI',
    iconSrc: 'https://flagcdn.com/w320/mw.png',
    code: '+265',
  },
  MYS: {
    label: 'Malaysia',
    value: 'MYS',
    iconSrc: 'https://flagcdn.com/w320/my.png',
    code: '+60',
  },
  MDV: {
    label: 'Maldives',
    value: 'MDV',
    iconSrc: 'https://flagcdn.com/w320/mv.png',
    code: '+960',
  },
  MLI: {
    label: 'Mali',
    value: 'MLI',
    iconSrc: 'https://flagcdn.com/w320/ml.png',
    code: '+223',
  },
  MLT: {
    label: 'Malta',
    value: 'MLT',
    iconSrc: 'https://flagcdn.com/w320/mt.png',
    code: '+356',
  },
  MHL: {
    label: 'Marshall Islands',
    value: 'MHL',
    iconSrc: 'https://flagcdn.com/w320/mh.png',
    code: '+692',
  },
  MTQ: {
    label: 'Martinique',
    value: 'MTQ',
    iconSrc: 'https://flagcdn.com/w320/mq.png',
    code: '+596',
  },
  MRT: {
    label: 'Mauritania',
    value: 'MRT',
    iconSrc: 'https://flagcdn.com/w320/mr.png',
    code: '+222',
  },
  MUS: {
    label: 'Mauritius',
    value: 'MUS',
    iconSrc: 'https://flagcdn.com/w320/mu.png',
    code: '+230',
  },
  MYT: {
    label: 'Mayotte',
    value: 'MYT',
    iconSrc: 'https://flagcdn.com/w320/yt.png',
    code: '+262',
  },
  MEX: {
    label: 'Mexico',
    value: 'MEX',
    iconSrc: 'https://flagcdn.com/w320/mx.png',
    code: '+52',
  },
  FSM: {
    label: 'Micronesia',
    value: 'FSM',
    iconSrc: 'https://flagcdn.com/w320/fm.png',
    code: '+691',
  },
  MDA: {
    label: 'Moldova',
    value: 'MDA',
    iconSrc: 'https://flagcdn.com/w320/md.png',
    code: '+373',
  },
  MCO: {
    label: 'Monaco',
    value: 'MCO',
    iconSrc: 'https://flagcdn.com/w320/mc.png',
    code: '+377',
  },
  MNG: {
    label: 'Mongolia',
    value: 'MNG',
    iconSrc: 'https://flagcdn.com/w320/mn.png',
    code: '+976',
  },
  MNE: {
    label: 'Montenegro',
    value: 'MNE',
    iconSrc: 'https://flagcdn.com/w320/me.png',
    code: '+382',
  },
  MSR: {
    label: 'Montserrat',
    value: 'MSR',
    iconSrc: 'https://flagcdn.com/w320/ms.png',
    code: '+1664',
  },
  MAR: {
    label: 'Morocco',
    value: 'MAR',
    iconSrc: 'https://flagcdn.com/w320/ma.png',
    code: '+212',
  },
  MOZ: {
    label: 'Mozambique',
    value: 'MOZ',
    iconSrc: 'https://flagcdn.com/w320/mz.png',
    code: '+258',
  },
  MMR: {
    label: 'Myanmar',
    value: 'MMR',
    iconSrc: 'https://flagcdn.com/w320/mm.png',
    code: '+95',
  },
  NAM: {
    label: 'Namibia',
    value: 'NAM',
    iconSrc: 'https://flagcdn.com/w320/na.png',
    code: '+264',
  },
  NRU: {
    label: 'Nauru',
    value: 'NRU',
    iconSrc: 'https://flagcdn.com/w320/nr.png',
    code: '+674',
  },
  NPL: {
    label: 'Nepal',
    value: 'NPL',
    iconSrc: 'https://flagcdn.com/w320/np.png',
    code: '+977',
  },
  NLD: {
    label: 'Netherlands',
    value: 'NLD',
    iconSrc: 'https://flagcdn.com/w320/nl.png',
    code: '+31',
  },
  NCL: {
    label: 'New Caledonia',
    value: 'NCL',
    iconSrc: 'https://flagcdn.com/w320/nc.png',
    code: '+687',
  },
  NZL: {
    label: 'New Zealand',
    value: 'NZL',
    iconSrc: 'https://flagcdn.com/w320/nz.png',
    code: '+64',
  },
  NIC: {
    label: 'Nicaragua',
    value: 'NIC',
    iconSrc: 'https://flagcdn.com/w320/ni.png',
    code: '+505',
  },
  NER: {
    label: 'Niger',
    value: 'NER',
    iconSrc: 'https://flagcdn.com/w320/ne.png',
    code: '+227',
  },
  NGA: {
    label: 'Nigeria',
    value: 'NGA',
    iconSrc: 'https://flagcdn.com/w320/ng.png',
    code: '+234',
  },
  NIU: {
    label: 'Niue',
    value: 'NIU',
    iconSrc: 'https://flagcdn.com/w320/nu.png',
    code: '+683',
  },
  NFK: {
    label: 'Norfolk Island',
    value: 'NFK',
    iconSrc: 'https://flagcdn.com/w320/nf.png',
    code: '+672',
  },
  PRK: {
    label: 'North Korea',
    value: 'PRK',
    iconSrc: 'https://flagcdn.com/w320/kp.png',
    code: '+850',
  },
  MKD: {
    label: 'North Macedonia',
    value: 'MKD',
    iconSrc: 'https://flagcdn.com/w320/mk.png',
    code: '+389',
  },
  MNP: {
    label: 'Northern Mariana Islands',
    value: 'MNP',
    iconSrc: 'https://flagcdn.com/w320/mp.png',
    code: '+1670',
  },
  NOR: {
    label: 'Norway',
    value: 'NOR',
    iconSrc: 'https://flagcdn.com/w320/no.png',
    code: '+47',
  },
  OMN: {
    label: 'Oman',
    value: 'OMN',
    iconSrc: 'https://flagcdn.com/w320/om.png',
    code: '+968',
  },
  PAK: {
    label: 'Pakistan',
    value: 'PAK',
    iconSrc: 'https://flagcdn.com/w320/pk.png',
    code: '+92',
  },
  PLW: {
    label: 'Palau',
    value: 'PLW',
    iconSrc: 'https://flagcdn.com/w320/pw.png',
    code: '+680',
  },
  PSE: {
    label: 'Palestine',
    value: 'PSE',
    iconSrc: 'https://flagcdn.com/w320/ps.png',
    code: '+970',
  },
  PAN: {
    label: 'Panama',
    value: 'PAN',
    iconSrc: 'https://flagcdn.com/w320/pa.png',
    code: '+507',
  },
  PNG: {
    label: 'Papua New Guinea',
    value: 'PNG',
    iconSrc: 'https://flagcdn.com/w320/pg.png',
    code: '+675',
  },
  PRY: {
    label: 'Paraguay',
    value: 'PRY',
    iconSrc: 'https://flagcdn.com/w320/py.png',
    code: '+595',
  },
  PER: {
    label: 'Peru',
    value: 'PER',
    iconSrc: 'https://flagcdn.com/w320/pe.png',
    code: '+51',
  },
  PHL: {
    label: 'Philippines',
    value: 'PHL',
    iconSrc: 'https://flagcdn.com/w320/ph.png',
    code: '+63',
  },
  PCN: {
    label: 'Pitcairn Islands',
    value: 'PCN',
    iconSrc: 'https://flagcdn.com/w320/pn.png',
    code: '+64',
  },
  POL: {
    label: 'Poland',
    value: 'POL',
    iconSrc: 'https://flagcdn.com/w320/pl.png',
    code: '+48',
  },
  PRT: {
    label: 'Portugal',
    value: 'PRT',
    iconSrc: 'https://flagcdn.com/w320/pt.png',
    code: '+351',
  },
  PRI: {
    label: 'Puerto Rico',
    value: 'PRI',
    iconSrc: 'https://flagcdn.com/w320/pr.png',
    code: '+1787,939',
  },
  QAT: {
    label: 'Qatar',
    value: 'QAT',
    iconSrc: 'https://flagcdn.com/w320/qa.png',
    code: '+974',
  },
  COG: {
    label: 'Republic of the Congo',
    value: 'COG',
    iconSrc: 'https://flagcdn.com/w320/cg.png',
    code: '+242',
  },
  REU: {
    label: 'Réunion',
    value: 'REU',
    iconSrc: 'https://flagcdn.com/w320/re.png',
    code: '+262',
  },
  ROU: {
    label: 'Romania',
    value: 'ROU',
    iconSrc: 'https://flagcdn.com/w320/ro.png',
    code: '+40',
  },
  RUS: {
    label: 'Russia',
    value: 'RUS',
    iconSrc: 'https://flagcdn.com/w320/ru.png',
    code: '+73,4,5,8,9',
  },
  RWA: {
    label: 'Rwanda',
    value: 'RWA',
    iconSrc: 'https://flagcdn.com/w320/rw.png',
    code: '+250',
  },
  BLM: {
    label: 'Saint Barthélemy',
    value: 'BLM',
    iconSrc: 'https://flagcdn.com/w320/bl.png',
    code: '+590',
  },
  SHN: {
    label: 'Saint Helena, Ascension and Tristan da Cunha',
    value: 'SHN',
    iconSrc: 'https://flagcdn.com/w320/sh.png',
    code: '+290,47',
  },
  KNA: {
    label: 'Saint Kitts and Nevis',
    value: 'KNA',
    iconSrc: 'https://flagcdn.com/w320/kn.png',
    code: '+1869',
  },
  LCA: {
    label: 'Saint Lucia',
    value: 'LCA',
    iconSrc: 'https://flagcdn.com/w320/lc.png',
    code: '+1758',
  },
  MAF: {
    label: 'Saint Martin',
    value: 'MAF',
    iconSrc: 'https://flagcdn.com/w320/mf.png',
    code: '+590',
  },
  SPM: {
    label: 'Saint Pierre and Miquelon',
    value: 'SPM',
    iconSrc: 'https://flagcdn.com/w320/pm.png',
    code: '+508',
  },
  VCT: {
    label: 'Saint Vincent and the Grenadines',
    value: 'VCT',
    iconSrc: 'https://flagcdn.com/w320/vc.png',
    code: '+1784',
  },
  WSM: {
    label: 'Samoa',
    value: 'WSM',
    iconSrc: 'https://flagcdn.com/w320/ws.png',
    code: '+685',
  },
  SMR: {
    label: 'San Marino',
    value: 'SMR',
    iconSrc: 'https://flagcdn.com/w320/sm.png',
    code: '+378',
  },
  STP: {
    label: 'São Tomé and Príncipe',
    value: 'STP',
    iconSrc: 'https://flagcdn.com/w320/st.png',
    code: '+239',
  },
  SAU: {
    label: 'Saudi Arabia',
    value: 'SAU',
    iconSrc: 'https://flagcdn.com/w320/sa.png',
    code: '+966',
  },
  SEN: {
    label: 'Senegal',
    value: 'SEN',
    iconSrc: 'https://flagcdn.com/w320/sn.png',
    code: '+221',
  },
  SRB: {
    label: 'Serbia',
    value: 'SRB',
    iconSrc: 'https://flagcdn.com/w320/rs.png',
    code: '+381',
  },
  SYC: {
    label: 'Seychelles',
    value: 'SYC',
    iconSrc: 'https://flagcdn.com/w320/sc.png',
    code: '+248',
  },
  SLE: {
    label: 'Sierra Leone',
    value: 'SLE',
    iconSrc: 'https://flagcdn.com/w320/sl.png',
    code: '+232',
  },
  SGP: {
    label: 'Singapore',
    value: 'SGP',
    iconSrc: 'https://flagcdn.com/w320/sg.png',
    code: '+65',
  },
  SXM: {
    label: 'Sint Maarten',
    value: 'SXM',
    iconSrc: 'https://flagcdn.com/w320/sx.png',
    code: '+1721',
  },
  SVK: {
    label: 'Slovakia',
    value: 'SVK',
    iconSrc: 'https://flagcdn.com/w320/sk.png',
    code: '+421',
  },
  SVN: {
    label: 'Slovenia',
    value: 'SVN',
    iconSrc: 'https://flagcdn.com/w320/si.png',
    code: '+386',
  },
  SLB: {
    label: 'Solomon Islands',
    value: 'SLB',
    iconSrc: 'https://flagcdn.com/w320/sb.png',
    code: '+677',
  },
  SOM: {
    label: 'Somalia',
    value: 'SOM',
    iconSrc: 'https://flagcdn.com/w320/so.png',
    code: '+252',
  },
  ZAF: {
    label: 'South Africa',
    value: 'ZAF',
    iconSrc: 'https://flagcdn.com/w320/za.png',
    code: '+27',
  },
  SGS: {
    label: 'South Georgia',
    value: 'SGS',
    iconSrc: 'https://flagcdn.com/w320/gs.png',
    code: '+500',
  },
  KOR: {
    label: 'South Korea',
    value: 'KOR',
    iconSrc: 'https://flagcdn.com/w320/kr.png',
    code: '+82',
  },
  SSD: {
    label: 'South Sudan',
    value: 'SSD',
    iconSrc: 'https://flagcdn.com/w320/ss.png',
    code: '+211',
  },
  ESP: {
    label: 'Spain',
    value: 'ESP',
    iconSrc: 'https://flagcdn.com/w320/es.png',
    code: '+34',
  },
  LKA: {
    label: 'Sri Lanka',
    value: 'LKA',
    iconSrc: 'https://flagcdn.com/w320/lk.png',
    code: '+94',
  },
  SDN: {
    label: 'Sudan',
    value: 'SDN',
    iconSrc: 'https://flagcdn.com/w320/sd.png',
    code: '+249',
  },
  SUR: {
    label: 'Suriname',
    value: 'SUR',
    iconSrc: 'https://flagcdn.com/w320/sr.png',
    code: '+597',
  },
  SJM: {
    label: 'Svalbard and Jan Mayen',
    value: 'SJM',
    iconSrc: 'https://flagcdn.com/w320/sj.png',
    code: '+4779',
  },
  SWE: {
    label: 'Sweden',
    value: 'SWE',
    iconSrc: 'https://flagcdn.com/w320/se.png',
    code: '+46',
  },
  CHE: {
    label: 'Switzerland',
    value: 'CHE',
    iconSrc: 'https://flagcdn.com/w320/ch.png',
    code: '+41',
  },
  SYR: {
    label: 'Syria',
    value: 'SYR',
    iconSrc: 'https://flagcdn.com/w320/sy.png',
    code: '+963',
  },
  TWN: {
    label: 'Taiwan',
    value: 'TWN',
    iconSrc: 'https://flagcdn.com/w320/tw.png',
    code: '+886',
  },
  TJK: {
    label: 'Tajikistan',
    value: 'TJK',
    iconSrc: 'https://flagcdn.com/w320/tj.png',
    code: '+992',
  },
  TZA: {
    label: 'Tanzania',
    value: 'TZA',
    iconSrc: 'https://flagcdn.com/w320/tz.png',
    code: '+255',
  },
  THA: {
    label: 'Thailand',
    value: 'THA',
    iconSrc: 'https://flagcdn.com/w320/th.png',
    code: '+66',
  },
  TLS: {
    label: 'Timor-Leste',
    value: 'TLS',
    iconSrc: 'https://flagcdn.com/w320/tl.png',
    code: '+670',
  },
  TGO: {
    label: 'Togo',
    value: 'TGO',
    iconSrc: 'https://flagcdn.com/w320/tg.png',
    code: '+228',
  },
  TKL: {
    label: 'Tokelau',
    value: 'TKL',
    iconSrc: 'https://flagcdn.com/w320/tk.png',
    code: '+690',
  },
  TON: {
    label: 'Tonga',
    value: 'TON',
    iconSrc: 'https://flagcdn.com/w320/to.png',
    code: '+676',
  },
  TTO: {
    label: 'Trinidad and Tobago',
    value: 'TTO',
    iconSrc: 'https://flagcdn.com/w320/tt.png',
    code: '+1868',
  },
  TUN: {
    label: 'Tunisia',
    value: 'TUN',
    iconSrc: 'https://flagcdn.com/w320/tn.png',
    code: '+216',
  },
  TUR: {
    label: 'Turkey',
    value: 'TUR',
    iconSrc: 'https://flagcdn.com/w320/tr.png',
    code: '+90',
  },
  TKM: {
    label: 'Turkmenistan',
    value: 'TKM',
    iconSrc: 'https://flagcdn.com/w320/tm.png',
    code: '+993',
  },
  TCA: {
    label: 'Turks and Caicos Islands',
    value: 'TCA',
    iconSrc: 'https://flagcdn.com/w320/tc.png',
    code: '+1649',
  },
  TUV: {
    label: 'Tuvalu',
    value: 'TUV',
    iconSrc: 'https://flagcdn.com/w320/tv.png',
    code: '+688',
  },
  UGA: {
    label: 'Uganda',
    value: 'UGA',
    iconSrc: 'https://flagcdn.com/w320/ug.png',
    code: '+256',
  },
  UKR: {
    label: 'Ukraine',
    value: 'UKR',
    iconSrc: 'https://flagcdn.com/w320/ua.png',
    code: '+380',
  },
  ARE: {
    label: 'United Arab Emirates',
    value: 'ARE',
    iconSrc: 'https://flagcdn.com/w320/ae.png',
    code: '+971',
  },
  GBR: {
    label: 'United Kingdom',
    value: 'GBR',
    iconSrc: 'https://flagcdn.com/w320/gb.png',
    code: '+44',
  },
  USA: {
    label: 'United States',
    value: 'USA',
    iconSrc: 'https://flagcdn.com/w320/us.png',
    code: `+1201,202,203,205,206,207,208,209,210,212,213,214,215,216,217,218,219,
    220,224,225,227,228,229,231,234,239,240,248,251,252,253,254,256,260,262,267,269,
    270,272,274,276,281,283,301,302,303,304,305,307,308,309,
    310,312,313,314,315,316,317,318,319,320,321,323,325,327,
    330,331,334,336,337,339,346,347,351,352,360,361,364,380,385,386,
    401,402,404,405,406,407,408,409,410,412,413,414,415,417,419,423,424,425,
    430,432,434,435,440,442,443,447,458,463,464,469,470,475,478,479,480,484,
    501,502,503,504,505,507,508,509,510,512,513,515,516,517,518,520,530,531,534,539,540,541,551,559,
    561,562,563,564,567,570,571,573,574,575,580,585,586,601,602,603,605,606,607,608,609,610,612,614,615,616,617,618,619,
    620,623,626,628,629,630,631,636,641,646,650,651,657,660,661,662,667,669,678,681,682,
    701,702,703,704,706,707,708,712,713,714,715,716,717,718,719,720,724,725,727,730,731,732,734,737,
    740,743,747,754,757,760,762,763,765,769,770,772,773,774,775,779,781,785,786,
    801,802,803,804,805,806,808,810,812,813,814,815,816,817,818,828,830,831,832,843,845,847,848,850,854,856,857,858,859,
    860,862,863,864,865,870,872,878,901,903,904,906,907,908,909,910,912,913,914,915,916,917,918,919,920,925,928,929,
    930,931,934,936,937,938,940,941,947,949,951,952,954,956,959,970,971,972,973,975,978,979,980,984,985,989`,
  },
  UMI: {
    label: 'United States Minor Outlying Islands',
    value: 'UMI',
    iconSrc: 'https://flagcdn.com/w320/um.png',
    code: '+268',
  },
  VIR: {
    label: 'United States Virgin Islands',
    value: 'VIR',
    iconSrc: 'https://flagcdn.com/w320/vi.png',
    code: '+1340',
  },
  URY: {
    label: 'Uruguay',
    value: 'URY',
    iconSrc: 'https://flagcdn.com/w320/uy.png',
    code: '+598',
  },
  UZB: {
    label: 'Uzbekistan',
    value: 'UZB',
    iconSrc: 'https://flagcdn.com/w320/uz.png',
    code: '+998',
  },
  VUT: {
    label: 'Vanuatu',
    value: 'VUT',
    iconSrc: 'https://flagcdn.com/w320/vu.png',
    code: '+678',
  },
  VAT: {
    label: 'Vatican City',
    value: 'VAT',
    iconSrc: 'https://flagcdn.com/w320/va.png',
    code: '+3906698,79',
  },
  VEN: {
    label: 'Venezuela',
    value: 'VEN',
    iconSrc: 'https://flagcdn.com/w320/ve.png',
    code: '+58',
  },
  VNM: {
    label: 'Vietnam',
    value: 'VNM',
    iconSrc: 'https://flagcdn.com/w320/vn.png',
    code: '+84',
  },
  WLF: {
    label: 'Wallis and Futuna',
    value: 'WLF',
    iconSrc: 'https://flagcdn.com/w320/wf.png',
    code: '+681',
  },
  ESH: {
    label: 'Western Sahara',
    value: 'ESH',
    iconSrc: 'https://flagcdn.com/w320/eh.png',
    code: '+2125288,125289',
  },
  YEM: {
    label: 'Yemen',
    value: 'YEM',
    iconSrc: 'https://flagcdn.com/w320/ye.png',
    code: '+967',
  },
  ZMB: {
    label: 'Zambia',
    value: 'ZMB',
    iconSrc: 'https://flagcdn.com/w320/zm.png',
    code: '+260',
  },
  ZWE: {
    label: 'Zimbabwe',
    value: 'ZWE',
    iconSrc: 'https://flagcdn.com/w320/zw.png',
    code: '+263',
  },
};

export { COUNTRIES };
